# -*- coding: utf-8 -*-
"""Trained_Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F2ptwbE5zkkM28A_gmzKNjN-KdpNBXMp

# Cell 1 — Imports & Setup
"""

import tensorflow as tf

print("TensorFlow Version:", tf.__version__)
print("Available GPUs:", tf.config.list_physical_devices('GPU'))

import pandas as pd
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
plt.show = lambda *args, **kwargs: None
plt.savefig = lambda *args, **kwargs: None
import seaborn as sns
from pathlib import Path


import xgboost as xgb
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Conv1D, LSTM, GRU, Dense, Dropout
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

pd.set_option('display.max_columns', None)
sns.set_style('whitegrid')
plt.rcParams['figure.figsize'] = (14, 6)

# Update these paths to wherever your files live locally
DAILY_PATH = "Delhi_day_ 2015-2020.xlsx"
HOURLY_PATH = "Delhi_hour_2015-2020.xlsx"

# from google.colab import drive
# drive.mount('/content/drive')

"""# Cell 2 — Load Data"""

daily = pd.read_excel(DAILY_PATH)
hourly = pd.read_excel(HOURLY_PATH)

# Standardize datetime column names for consistency downstream
daily = daily.rename(columns={"Date": "datetime"})
hourly = hourly.rename(columns={"Datetime": "datetime"})

daily["datetime"] = pd.to_datetime(daily["datetime"])
hourly["datetime"] = pd.to_datetime(hourly["datetime"])

daily = daily.sort_values("datetime").reset_index(drop=True)
hourly = hourly.sort_values("datetime").reset_index(drop=True)

print("Daily shape:", daily.shape)
print("Hourly shape:", hourly.shape)
print("\nDaily date range:", daily['datetime'].min(), "to", daily['datetime'].max())
print("Hourly date range:", hourly['datetime'].min(), "to", hourly['datetime'].max())

"""# Cell 3 — Initial Inspection"""

print("=== DAILY DATASET ===")
print(daily.info())
print("\n=== DAILY DESCRIBE ===")
print(daily.describe())

print("\n\n=== HOURLY DATASET ===")
print(hourly.info())
print("\n=== HOURLY DESCRIBE ===")
print(hourly.describe())

"""# Cell 4 — Missing Value Summary (Table)"""

def missing_report(df, name):
    miss = df.isna().sum()
    pct = (miss / len(df) * 100).round(2)
    report = pd.DataFrame({"missing_count": miss, "missing_pct": pct})
    report = report[report["missing_count"] > 0].sort_values("missing_pct", ascending=False)
    print(f"\n--- Missing values in {name} ---")
    print(report)
    return report

daily_missing = missing_report(daily, "Daily")
hourly_missing = missing_report(hourly, "Hourly")

"""# Cell 5 — Missing Value Heatmaps"""

fig, axes = plt.subplots(1, 2, figsize=(18, 6))

sns.heatmap(daily.drop(columns=["City", "datetime"]).isna(),
            cbar=False, cmap="viridis", ax=axes[0])
axes[0].set_title("Missing Values — Daily Dataset")

sns.heatmap(hourly.drop(columns=["City", "datetime"]).isna(),
            cbar=False, cmap="viridis", ax=axes[1])
axes[1].set_title("Missing Values — Hourly Dataset")

plt.tight_layout()
plt.savefig("missing_heatmap.png", dpi=150)
plt.show()

"""# Cell 6 — Pollutant Column List & Xylene Decision"""

pollutant_cols = ["PM2.5", "PM10", "NO", "NO2", "NOx", "NH3",
                  "CO", "SO2", "O3", "Benzene", "Toluene", "Xylene"]

# Drop Xylene — too sparse (~39% missing in both datasets) to impute reliably
daily = daily.drop(columns=["Xylene"])
hourly = hourly.drop(columns=["Xylene"])
pollutant_cols.remove("Xylene")

print("Remaining pollutant features:", pollutant_cols)

"""# Cell 7 — Missing Value Handling (Time-Aware Interpolation)"""

def handle_missing(df, cols, datetime_col="datetime"):
    df = df.set_index(datetime_col)
    # Time-based linear interpolation for pollutant + AQI columns
    df[cols + ["AQI"]] = df[cols + ["AQI"]].interpolate(method="time", limit_direction="both")
    df = df.reset_index()
    return df

daily = handle_missing(daily, pollutant_cols)
hourly = handle_missing(hourly, pollutant_cols)

# Recompute AQI_Bucket for rows where AQI was imputed but bucket is still missing
def aqi_bucket(aqi):
    if pd.isna(aqi): return np.nan
    if aqi <= 50: return "Good"
    elif aqi <= 100: return "Satisfactory"
    elif aqi <= 200: return "Moderate"
    elif aqi <= 300: return "Poor"
    elif aqi <= 400: return "Very Poor"
    else: return "Severe"

daily["AQI_Bucket"] = daily["AQI_Bucket"].fillna(daily["AQI"].apply(aqi_bucket))
hourly["AQI_Bucket"] = hourly["AQI_Bucket"].fillna(hourly["AQI"].apply(aqi_bucket))

print("Remaining missing values (daily):", daily.isna().sum().sum())
print("Remaining missing values (hourly):", hourly.isna().sum().sum())

"""# Cell 8 — Outlier Detection (IQR-based, visual)"""

fig, axes = plt.subplots(3, 4, figsize=(20, 12))
axes = axes.flatten()

for i, col in enumerate(pollutant_cols):
    sns.boxplot(y=daily[col], ax=axes[i], color="skyblue")
    axes[i].set_title(f"Daily — {col}")

plt.tight_layout()
plt.savefig("outlier_boxplots_daily.png", dpi=150)
plt.show()

# IQR-based outlier counts
def iqr_outlier_report(df, cols):
    rows = []
    for col in cols:
        Q1, Q3 = df[col].quantile([0.25, 0.75])
        IQR = Q3 - Q1
        lower, upper = Q1 - 1.5 * IQR, Q3 + 1.5 * IQR
        n_outliers = ((df[col] < lower) | (df[col] > upper)).sum()
        rows.append([col, lower, upper, n_outliers])
    return pd.DataFrame(rows, columns=["column", "lower_bound", "upper_bound", "n_outliers"])

print(iqr_outlier_report(daily, pollutant_cols))

"""# Cell 9 — Outlier Treatment (Capping, not deletion)"""

def cap_outliers(df, cols):
    df = df.copy()
    for col in cols:
        Q1, Q3 = df[col].quantile([0.25, 0.75])
        IQR = Q3 - Q1
        lower, upper = Q1 - 1.5 * IQR, Q3 + 1.5 * IQR
        df[col] = df[col].clip(lower=lower, upper=upper)
    return df

daily = cap_outliers(daily, pollutant_cols + ["AQI"])
hourly = cap_outliers(hourly, pollutant_cols + ["AQI"])

print("Outlier treatment complete.")

"""# Cell 10 — AQI Trend Visualization"""

fig, axes = plt.subplots(2, 1, figsize=(16, 10))

axes[0].plot(daily["datetime"], daily["AQI"], color="darkred", linewidth=0.8)
axes[0].set_title("Daily AQI Trend — Delhi (2015–2020)")
axes[0].set_ylabel("AQI")

axes[1].plot(hourly["datetime"], hourly["AQI"], color="steelblue", linewidth=0.3)
axes[1].set_title("Hourly AQI Trend — Delhi (2015–2020)")
axes[1].set_ylabel("AQI")

plt.tight_layout()
plt.savefig("aqi_trend.png", dpi=150)
plt.show()

"""# Cell 11 — Correlation Heatmap"""

fig, axes = plt.subplots(1, 2, figsize=(20, 8))

sns.heatmap(daily[pollutant_cols + ["AQI"]].corr(), annot=True, fmt=".2f",
            cmap="coolwarm", ax=axes[0])
axes[0].set_title("Correlation Heatmap — Daily")

sns.heatmap(hourly[pollutant_cols + ["AQI"]].corr(), annot=True, fmt=".2f",
            cmap="coolwarm", ax=axes[1])
axes[1].set_title("Correlation Heatmap — Hourly")

plt.tight_layout()
plt.savefig("correlation_heatmap.png", dpi=150)
plt.show()

"""# Cell 12 — AQI Bucket Distribution & Seasonal Pattern"""

fig, axes = plt.subplots(1, 2, figsize=(16, 6))

daily["AQI_Bucket"].value_counts().plot(kind="bar", ax=axes[0], color="teal")
axes[0].set_title("AQI Bucket Distribution — Daily")
axes[0].tick_params(axis='x', rotation=45)

daily["month"] = daily["datetime"].dt.month
monthly_avg = daily.groupby("month")["AQI"].mean()
monthly_avg.plot(kind="bar", ax=axes[1], color="orange")
axes[1].set_title("Average AQI by Month (Seasonality)")
axes[1].set_xlabel("Month")

plt.tight_layout()
plt.savefig("aqi_distribution_seasonality.png", dpi=150)
plt.show()

"""# Cell 13 — Save Cleaned Data"""

daily.to_csv("delhi_daily_cleaned.csv", index=False)
hourly.to_csv("delhi_hourly_cleaned.csv", index=False)

print("Cleaned datasets saved:")
print(" - delhi_daily_cleaned.csv:", daily.shape)
print(" - delhi_hourly_cleaned.csv:", hourly.shape)

"""# Cell 14 — Load Cleaned Data & Calendar Features"""

daily = pd.read_csv("delhi_daily_cleaned.csv", parse_dates=["datetime"])
hourly = pd.read_csv("delhi_hourly_cleaned.csv", parse_dates=["datetime"])

def add_calendar_features(df, dt_col="datetime"):
    df = df.copy()
    df["month"] = df[dt_col].dt.month
    df["weekday"] = df[dt_col].dt.weekday          # 0=Mon ... 6=Sun
    df["is_weekend"] = (df["weekday"] >= 5).astype(int)
    df["day_of_year"] = df[dt_col].dt.dayofyear

    def get_season(month):
        if month in [12, 1, 2]: return 0   # Winter
        elif month in [3, 4, 5]: return 1  # Summer
        elif month in [6, 7, 8, 9]: return 2  # Monsoon
        else: return 3                      # Post-monsoon/Autumn
    df["season"] = df["month"].apply(get_season)
    return df

daily = add_calendar_features(daily)
hourly = add_calendar_features(hourly)

# Hourly gets an extra feature — hour of day matters a lot for AQI (rush hour, etc.)
hourly["hour"] = hourly["datetime"].dt.hour

print(daily[["datetime", "month", "weekday", "is_weekend", "season"]].head())
print(hourly[["datetime", "hour", "month", "weekday", "is_weekend", "season"]].head())

"""# Cell 15 — Lag Features"""

def add_lag_features(df, target_col, lags):
    df = df.copy()
    for lag in lags:
        df[f"{target_col}_lag{lag}"] = df[target_col].shift(lag)
    return df

# Daily: as specified in project plan
daily = add_lag_features(daily, "AQI", lags=[1, 2, 3, 7, 14, 30])

# Hourly: shorter horizon appropriate for hourly resolution
hourly = add_lag_features(hourly, "AQI", lags=[1, 2, 3, 6, 12, 24])

print("Daily lag columns:", [c for c in daily.columns if "lag" in c])
print("Hourly lag columns:", [c for c in hourly.columns if "lag" in c])

"""# Cell 16 — Rolling Window Features"""

def add_rolling_features(df, target_col, windows):
    df = df.copy()
    for w in windows:
        df[f"{target_col}_rollmean{w}"] = df[target_col].shift(1).rolling(window=w).mean()
        df[f"{target_col}_rollstd{w}"]  = df[target_col].shift(1).rolling(window=w).std()
        df[f"{target_col}_rollmax{w}"]  = df[target_col].shift(1).rolling(window=w).max()
        df[f"{target_col}_rollmin{w}"]  = df[target_col].shift(1).rolling(window=w).min()
    return df

# Daily: 3-day, 7-day, 14-day windows (as per spec)
daily = add_rolling_features(daily, "AQI", windows=[3, 7, 14])

# Hourly: 6-hr, 12-hr, 24-hr windows (resolution-appropriate)
hourly = add_rolling_features(hourly, "AQI", windows=[6, 12, 24])

print("Daily rolling columns:", [c for c in daily.columns if "roll" in c])

"""# Cell 17 — Drop Rows with NaN from Lag/Rolling Generation"""

print("Daily shape before dropna:", daily.shape)
daily = daily.dropna().reset_index(drop=True)
print("Daily shape after dropna:", daily.shape)

print("\nHourly shape before dropna:", hourly.shape)
hourly = hourly.dropna().reset_index(drop=True)
print("Hourly shape after dropna:", hourly.shape)

"""# Cell 18 — Chronological Train/Validation/Test Split (No Shuffling!)"""

def chronological_split(df, train_frac=0.70, val_frac=0.15):
    n = len(df)
    train_end = int(n * train_frac)
    val_end = int(n * (train_frac + val_frac))
    train = df.iloc[:train_end].reset_index(drop=True)
    val   = df.iloc[train_end:val_end].reset_index(drop=True)
    test  = df.iloc[val_end:].reset_index(drop=True)
    return train, val, test

daily_train, daily_val, daily_test = chronological_split(daily)
hourly_train, hourly_val, hourly_test = chronological_split(hourly)

print("Daily  -> train:", daily_train.shape, "val:", daily_val.shape, "test:", daily_test.shape)
print("Hourly -> train:", hourly_train.shape, "val:", hourly_val.shape, "test:", hourly_test.shape)

print("\nDaily train range:", daily_train['datetime'].min(), "to", daily_train['datetime'].max())
print("Daily val range:  ", daily_val['datetime'].min(), "to", daily_val['datetime'].max())
print("Daily test range: ", daily_test['datetime'].min(), "to", daily_test['datetime'].max())

"""# Cell 19 — Feature Scaling (Fit on Train Only)"""

from sklearn.preprocessing import MinMaxScaler
import joblib

# Identify feature columns (exclude identifiers/target/text columns)
exclude_cols = ["datetime", "City", "AQI_Bucket", "AQI"]

daily_feature_cols = [c for c in daily.columns if c not in exclude_cols]
hourly_feature_cols = [c for c in hourly.columns if c not in exclude_cols]

# --- Daily scaler ---
daily_scaler_X = MinMaxScaler()
daily_scaler_y = MinMaxScaler()

daily_train_X = daily_scaler_X.fit_transform(daily_train[daily_feature_cols])
daily_val_X   = daily_scaler_X.transform(daily_val[daily_feature_cols])
daily_test_X  = daily_scaler_X.transform(daily_test[daily_feature_cols])

daily_train_y = daily_scaler_y.fit_transform(daily_train[["AQI"]])
daily_val_y   = daily_scaler_y.transform(daily_val[["AQI"]])
daily_test_y  = daily_scaler_y.transform(daily_test[["AQI"]])

# --- Hourly scaler ---
hourly_scaler_X = MinMaxScaler()
hourly_scaler_y = MinMaxScaler()

hourly_train_X = hourly_scaler_X.fit_transform(hourly_train[hourly_feature_cols])
hourly_val_X   = hourly_scaler_X.transform(hourly_val[hourly_feature_cols])
hourly_test_X  = hourly_scaler_X.transform(hourly_test[hourly_feature_cols])

hourly_train_y = hourly_scaler_y.fit_transform(hourly_train[["AQI"]])
hourly_val_y   = hourly_scaler_y.transform(hourly_val[["AQI"]])
hourly_test_y  = hourly_scaler_y.transform(hourly_test[["AQI"]])

# Save scalers — you'll need these later for inverse-transforming predictions
joblib.dump(daily_scaler_X, "daily_scaler_X.pkl")
joblib.dump(daily_scaler_y, "daily_scaler_y.pkl")
joblib.dump(hourly_scaler_X, "hourly_scaler_X.pkl")
joblib.dump(hourly_scaler_y, "hourly_scaler_y.pkl")

print("Daily feature count:", len(daily_feature_cols))
print("Hourly feature count:", len(hourly_feature_cols))

"""# Cell 20 — Sliding Window Generator (for CNN-LSTM-GRU on Hourly Data)"""

def create_sequences(X, y, window_size=24):
    """
    X: 2D array (n_samples, n_features), already scaled
    y: 2D array (n_samples, 1), already scaled
    window_size: how many past timesteps to look back
    Returns X_seq: (n_samples - window_size, window_size, n_features)
            y_seq: (n_samples - window_size,)
    """
    X_seq, y_seq = [], []
    for i in range(window_size, len(X)):
        X_seq.append(X[i - window_size:i])
        y_seq.append(y[i])
    return np.array(X_seq), np.array(y_seq)

WINDOW_SIZE = 24  # use past 24 hours to predict next hour

X_train_seq, y_train_seq = create_sequences(hourly_train_X, hourly_train_y, WINDOW_SIZE)
X_val_seq, y_val_seq     = create_sequences(hourly_val_X, hourly_val_y, WINDOW_SIZE)
X_test_seq, y_test_seq   = create_sequences(hourly_test_X, hourly_test_y, WINDOW_SIZE)

print("X_train_seq:", X_train_seq.shape)
print("y_train_seq:", y_train_seq.shape)
print("X_val_seq:  ", X_val_seq.shape)
print("X_test_seq: ", X_test_seq.shape)

"""# Cell 21 — Save Everything for Next Stage"""

import numpy as np

# Save sequence arrays for CNN-LSTM-GRU
np.savez("hourly_sequences.npz",
         X_train=X_train_seq, y_train=y_train_seq,
         X_val=X_val_seq, y_val=y_val_seq,
         X_test=X_test_seq, y_test=y_test_seq)

# Save tabular arrays for XGBoost (daily)
np.savez("daily_tabular.npz",
         X_train=daily_train_X, y_train=daily_train_y,
         X_val=daily_val_X, y_val=daily_val_y,
         X_test=daily_test_X, y_test=daily_test_y)

# Save feature column names for reference (feature importance plots later need these)
import json
with open("feature_columns.json", "w") as f:
    json.dump({"daily": daily_feature_cols, "hourly": hourly_feature_cols}, f)

print("Feature engineering complete. Files saved:")
print(" - hourly_sequences.npz  (for CNN-LSTM-GRU)")
print(" - daily_tabular.npz     (for XGBoost)")
print(" - feature_columns.json")
print(" - *.pkl scalers")

"""# Cell 22 — Imports for Deep Learning"""

import tensorflow as tf
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Conv1D, MaxPooling1D, LSTM, GRU, Dense, Dropout, Input
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint, ReduceLROnPlateau
from tensorflow.keras.optimizers import Adam

tf.random.set_seed(42)
np.random.seed(42)

print("TensorFlow version:", tf.__version__)
print("GPU available:", tf.config.list_physical_devices('GPU'))

"""# Cell 23 — Load Sequence Data (if resuming from saved files)"""

seq_data = np.load("hourly_sequences.npz")
X_train_seq, y_train_seq = seq_data["X_train"], seq_data["y_train"]
X_val_seq, y_val_seq     = seq_data["X_val"], seq_data["y_val"]
X_test_seq, y_test_seq   = seq_data["X_test"], seq_data["y_test"]

n_timesteps = X_train_seq.shape[1]
n_features  = X_train_seq.shape[2]

print(f"Timesteps: {n_timesteps}, Features: {n_features}")
print("X_train_seq:", X_train_seq.shape, " y_train_seq:", y_train_seq.shape)

"""# Cell 24 — Build CNN-LSTM-GRU Model"""

def build_cnn_lstm_gru(n_timesteps, n_features):
    model = Sequential([
        Input(shape=(n_timesteps, n_features)),

        Conv1D(filters=64, kernel_size=3, activation='relu', padding='same'),
        MaxPooling1D(pool_size=2),

        LSTM(64, return_sequences=True),
        Dropout(0.2),

        GRU(32, return_sequences=False),
        Dropout(0.2),

        Dense(16, activation='relu'),
        Dense(1)  # linear output for regression
    ])

    model.compile(
        optimizer=Adam(learning_rate=0.001),
        loss='mse',
        metrics=['mae']
    )
    return model

model = build_cnn_lstm_gru(n_timesteps, n_features)
model.summary()

"""# Cell 25 — Training Callbacks & Model Training"""

callbacks = [
    EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True, verbose=1),
    ModelCheckpoint("best_cnn_lstm_gru.keras", monitor='val_loss', save_best_only=True, verbose=1),
    ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=5, min_lr=1e-6, verbose=1)
]

history = model.fit(
    X_train_seq, y_train_seq,
    validation_data=(X_val_seq, y_val_seq),
    epochs=1,
    batch_size=64,
    callbacks=callbacks,
    verbose=1
)

"""# Cell 26 — Training vs Validation Loss Plot"""

fig, axes = plt.subplots(1, 2, figsize=(16, 5))

axes[0].plot(history.history['loss'], label='Train Loss')
axes[0].plot(history.history['val_loss'], label='Validation Loss')
axes[0].set_title('Training vs Validation Loss (MSE)')
axes[0].set_xlabel('Epoch')
axes[0].set_ylabel('Loss')
axes[0].legend()

axes[1].plot(history.history['mae'], label='Train MAE')
axes[1].plot(history.history['val_mae'], label='Validation MAE')
axes[1].set_title('Training vs Validation MAE')
axes[1].set_xlabel('Epoch')
axes[1].set_ylabel('MAE')
axes[1].legend()

plt.tight_layout()
plt.savefig("cnn_lstm_gru_loss_curves.png", dpi=150)
plt.show()

"""# Cell 27 — Hyperparameter Tuning with Keras Tuner"""

# pip install keras-tuner

# pip install keras-tuner if not already installed
import keras_tuner as kt

def build_tunable_model(hp):
    model = Sequential()
    model.add(Input(shape=(n_timesteps, n_features)))

    model.add(Conv1D(
        filters=hp.Choice('conv_filters', [32, 64, 128]),
        kernel_size=hp.Choice('kernel_size', [2, 3, 5]),
        activation='relu', padding='same'
    ))
    model.add(MaxPooling1D(pool_size=2))

    model.add(LSTM(
        units=hp.Choice('lstm_units', [32, 64, 128]),
        return_sequences=True
    ))
    model.add(Dropout(hp.Float('dropout1', 0.1, 0.4, step=0.1)))

    model.add(GRU(units=hp.Choice('gru_units', [16, 32, 64]), return_sequences=False))
    model.add(Dropout(hp.Float('dropout2', 0.1, 0.4, step=0.1)))

    model.add(Dense(16, activation='relu'))
    model.add(Dense(1))

    model.compile(
        optimizer=Adam(learning_rate=hp.Choice('lr', [0.01, 0.001, 0.0005])),
        loss='mse', metrics=['mae']
    )
    return model

tuner = kt.RandomSearch(
    build_tunable_model,
    objective='val_loss',
    max_trials=1,
    executions_per_trial=1,
    directory='tuner_results',
    project_name='cnn_lstm_gru_aqi'
)

tuner.search(
    X_train_seq, y_train_seq,
    validation_data=(X_val_seq, y_val_seq),
    epochs=1,
    batch_size=64,
    callbacks=[EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)],
    verbose=1
)

best_hp = tuner.get_best_hyperparameters(1)[0]
print("Best hyperparameters found:")
for param in best_hp.values:
    print(f"  {param}: {best_hp.values[param]}")

best_model = tuner.get_best_models(1)[0]

"""# Cell 28 — Retrain Best Model on Full Config & Generate Predictions"""

# Use the tuned model if you ran Cell 27, otherwise fall back to Cell 24's model
final_dl_model = best_model if 'best_model' in dir() else model

# Predictions (still in scaled space)
y_train_pred_scaled = final_dl_model.predict(X_train_seq)
y_val_pred_scaled   = final_dl_model.predict(X_val_seq)
y_test_pred_scaled  = final_dl_model.predict(X_test_seq)

# Inverse transform back to real AQI values
hourly_scaler_y = joblib.load("hourly_scaler_y.pkl")

y_train_actual = hourly_scaler_y.inverse_transform(y_train_seq)
y_val_actual   = hourly_scaler_y.inverse_transform(y_val_seq)
y_test_actual  = hourly_scaler_y.inverse_transform(y_test_seq)

y_train_pred = hourly_scaler_y.inverse_transform(y_train_pred_scaled)
y_val_pred   = hourly_scaler_y.inverse_transform(y_val_pred_scaled)
y_test_pred  = hourly_scaler_y.inverse_transform(y_test_pred_scaled)

final_dl_model.save("final_cnn_lstm_gru.keras")
print("CNN-LSTM-GRU model trained, saved, and predictions generated.")

"""# Cell 29 — Actual vs Predicted Plot (Deep Learning Model)"""

plt.figure(figsize=(16, 6))
plt.plot(y_test_actual[:500], label='Actual AQI', color='black', linewidth=1)
plt.plot(y_test_pred[:500], label='Predicted AQI (CNN-LSTM-GRU)', color='crimson', linewidth=1, alpha=0.8)
plt.title('Actual vs Predicted AQI — Test Set (first 500 hours) — CNN-LSTM-GRU')
plt.xlabel('Time Step')
plt.ylabel('AQI')
plt.legend()
plt.tight_layout()
plt.savefig("cnn_lstm_gru_actual_vs_predicted.png", dpi=150)
plt.show()

"""# Cell 30 — Imports & Load Daily Tabular Data"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install xgboost

import xgboost as xgb
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import time

tabular_data = np.load("daily_tabular.npz")
daily_train_X, daily_train_y = tabular_data["X_train"], tabular_data["y_train"]
daily_val_X, daily_val_y     = tabular_data["X_val"], tabular_data["y_val"]
daily_test_X, daily_test_y   = tabular_data["X_test"], tabular_data["y_test"]

daily_scaler_y = joblib.load("daily_scaler_y.pkl")

print("Daily train:", daily_train_X.shape, " val:", daily_val_X.shape, " test:", daily_test_X.shape)

"""# Cell 31 — Baseline XGBoost Model"""

xgb_model = xgb.XGBRegressor(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=5,
    subsample=0.8,
    colsample_bytree=0.8,
    objective='reg:squarederror',
    random_state=42,
    early_stopping_rounds=20,
    eval_metric='rmse'
)

start_time = time.time()
xgb_model.fit(
    daily_train_X, daily_train_y.ravel(),
    eval_set=[(daily_val_X, daily_val_y.ravel())],
    verbose=True
)
xgb_train_time = time.time() - start_time

print(f"\nXGBoost training time: {xgb_train_time:.2f} seconds")

"""# Cell 32 — Hyperparameter Tuning with RandomizedSearchCV"""

from sklearn.model_selection import RandomizedSearchCV, TimeSeriesSplit

param_dist = {
    'n_estimators': [100, 200, 300, 500],
    'max_depth': [3, 4, 5, 6, 8],
    'learning_rate': [0.01, 0.03, 0.05, 0.1],
    'subsample': [0.6, 0.7, 0.8, 0.9, 1.0],
    'colsample_bytree': [0.6, 0.7, 0.8, 0.9, 1.0],
    'min_child_weight': [1, 3, 5],
    'gamma': [0, 0.1, 0.3]
}

tscv = TimeSeriesSplit(n_splits=5)

base_model = xgb.XGBRegressor(objective='reg:squarederror', random_state=42)

random_search = RandomizedSearchCV(
    estimator=base_model,
    param_distributions=param_dist,
    n_iter=40,
    scoring='neg_mean_squared_error',
    cv=tscv,
    verbose=1,
    random_state=42,
    n_jobs=-1
)

random_search.fit(daily_train_X, daily_train_y.ravel())

print("Best parameters found:")
print(random_search.best_params_)
print("Best CV score (neg MSE):", random_search.best_score_)

"""# Cell 33 — Train Final Tuned XGBoost Model"""

best_params = random_search.best_params_

final_xgb_model = xgb.XGBRegressor(
    **best_params,
    objective='reg:squarederror',
    random_state=42,
    early_stopping_rounds=20,
    eval_metric='rmse'
)

start_time = time.time()
final_xgb_model.fit(
    daily_train_X, daily_train_y.ravel(),
    eval_set=[(daily_val_X, daily_val_y.ravel())],
    verbose=False
)
xgb_train_time = time.time() - start_time

final_xgb_model.save_model("final_xgboost_model.json")
print(f"Final XGBoost trained in {xgb_train_time:.2f} seconds and saved.")

"""# Cell 34 — XGBoost Predictions & Inverse Transform"""

start_time = time.time()
xgb_test_pred_scaled = final_xgb_model.predict(daily_test_X).reshape(-1, 1)
xgb_inference_time = time.time() - start_time

xgb_train_pred_scaled = final_xgb_model.predict(daily_train_X).reshape(-1, 1)
xgb_val_pred_scaled   = final_xgb_model.predict(daily_val_X).reshape(-1, 1)

# Inverse transform to real AQI scale
xgb_train_actual = daily_scaler_y.inverse_transform(daily_train_y)
xgb_val_actual    = daily_scaler_y.inverse_transform(daily_val_y)
xgb_test_actual   = daily_scaler_y.inverse_transform(daily_test_y)

xgb_train_pred = daily_scaler_y.inverse_transform(xgb_train_pred_scaled)
xgb_val_pred    = daily_scaler_y.inverse_transform(xgb_val_pred_scaled)
xgb_test_pred   = daily_scaler_y.inverse_transform(xgb_test_pred_scaled)

print(f"XGBoost inference time for {len(daily_test_X)} samples: {xgb_inference_time:.4f} seconds")

"""# Cell 35 — Feature Importance Plot"""

with open("feature_columns.json") as f:
    feature_cols = json.load(f)
daily_feature_cols = feature_cols["daily"]

importance = final_xgb_model.feature_importances_
imp_df = pd.DataFrame({"feature": daily_feature_cols, "importance": importance})
imp_df = imp_df.sort_values("importance", ascending=False).head(15)

plt.figure(figsize=(10, 8))
sns.barplot(data=imp_df, x="importance", y="feature", palette="viridis")
plt.title("Top 15 Feature Importances — XGBoost (Daily AQI)")
plt.xlabel("Importance Score")
plt.tight_layout()
plt.savefig("xgboost_feature_importance.png", dpi=150)
plt.show()

"""# Cell 36 — Actual vs Predicted Plot (XGBoost)"""

plt.figure(figsize=(16, 6))
plt.plot(xgb_test_actual, label='Actual AQI', color='black', linewidth=1.2)
plt.plot(xgb_test_pred, label='Predicted AQI (XGBoost)', color='green', linewidth=1.2, alpha=0.8)
plt.title('Actual vs Predicted AQI — Test Set — XGBoost (Daily)')
plt.xlabel('Day Index')
plt.ylabel('AQI')
plt.legend()
plt.tight_layout()
plt.savefig("xgboost_actual_vs_predicted.png", dpi=150)
plt.show()

"""# Cell 37 — Residual Plot (XGBoost)"""

residuals = xgb_test_actual.flatten() - xgb_test_pred.flatten()

fig, axes = plt.subplots(1, 2, figsize=(16, 5))

axes[0].scatter(xgb_test_pred, residuals, alpha=0.5, color='purple')
axes[0].axhline(0, color='red', linestyle='--')
axes[0].set_title('Residuals vs Predicted — XGBoost')
axes[0].set_xlabel('Predicted AQI')
axes[0].set_ylabel('Residual')

sns.histplot(residuals, kde=True, ax=axes[1], color='purple')
axes[1].set_title('Residual Distribution — XGBoost')

plt.tight_layout()
plt.savefig("xgboost_residuals.png", dpi=150)
plt.show()

"""# Cell 38 — Recover Datetimes for Hourly Val/Test Predictions"""

# Re-load hourly splits (pre-scaling) to get datetime column back in the same order
hourly_full = pd.read_csv("delhi_hourly_cleaned.csv", parse_dates=["datetime"])
# Re-run same calendar/lag/rolling feature steps happened before split — datetime order is unchanged,
# so we can re-derive train/val/test datetime slices with the same chronological_split logic.

def chronological_split(df, train_frac=0.70, val_frac=0.15):
    n = len(df)
    train_end = int(n * train_frac)
    val_end = int(n * (train_frac + val_frac))
    return df.iloc[:train_end].reset_index(drop=True), \
           df.iloc[train_end:val_end].reset_index(drop=True), \
           df.iloc[val_end:].reset_index(drop=True)

# NOTE: this must match the row count of hourly_train/val/test used earlier (post feature-engineering + dropna).
# If Cell 17/18 already produced hourly_train/val/test in memory, just reuse those directly instead:
hourly_val_dates  = hourly_val["datetime"].values
hourly_test_dates = hourly_test["datetime"].values

# Sequence creation drops the first WINDOW_SIZE rows of each split
WINDOW_SIZE = 24
val_dates_seq  = hourly_val_dates[WINDOW_SIZE:]
test_dates_seq = hourly_test_dates[WINDOW_SIZE:]

print("val_dates_seq matches y_val_pred rows:", len(val_dates_seq) == len(y_val_pred))
print("test_dates_seq matches y_test_pred rows:", len(test_dates_seq) == len(y_test_pred))

"""# Cell 39 — Aggregate Hourly Predictions to Daily"""

def aggregate_hourly_to_daily(dates, values):
    df = pd.DataFrame({"date": pd.to_datetime(dates), "value": values.flatten()})
    df["date"] = df["date"].dt.floor("D")
    daily_agg = df.groupby("date")["value"].mean().reset_index()
    return daily_agg

dl_val_daily  = aggregate_hourly_to_daily(val_dates_seq, y_val_pred)
dl_test_daily = aggregate_hourly_to_daily(test_dates_seq, y_test_pred)

dl_val_daily.columns  = ["date", "dl_pred_aqi"]
dl_test_daily.columns = ["date", "dl_pred_aqi"]

print(dl_test_daily.head())
print("Daily-aggregated DL predictions — val:", dl_val_daily.shape, " test:", dl_test_daily.shape)

"""# Cell 40 — Align with XGBoost Daily Predictions (Overlapping Dates Only)"""

xgb_val_df = pd.DataFrame({
    "date": pd.to_datetime(daily_val["datetime"]).dt.floor("D"),
    "xgb_pred_aqi": xgb_val_pred.flatten(),
    "actual_aqi": xgb_val_actual.flatten()
})

xgb_test_df = pd.DataFrame({
    "date": pd.to_datetime(daily_test["datetime"]).dt.floor("D"),
    "xgb_pred_aqi": xgb_test_pred.flatten(),
    "actual_aqi": xgb_test_actual.flatten()
})

# Inner join keeps only dates present in BOTH the hourly-aggregated and daily predictions
val_merged  = pd.merge(xgb_val_df, dl_val_daily, on="date", how="inner")
test_merged = pd.merge(xgb_test_df, dl_test_daily, on="date", how="inner")

print("Overlapping validation dates:", val_merged.shape[0])
print("Overlapping test dates:", test_merged.shape[0])
print(test_merged.head())

"""# Cell 41 — Find Optimal Ensemble Weights (Minimize Validation Error)"""

from scipy.optimize import minimize_scalar

def ensemble_val_rmse(w1):
    w2 = 1 - w1
    ensemble_pred = w1 * val_merged["dl_pred_aqi"] + w2 * val_merged["xgb_pred_aqi"]
    return np.sqrt(mean_squared_error(val_merged["actual_aqi"], ensemble_pred))

# Grid search for interpretability + a quick scalar minimize for precision
weights_grid = np.linspace(0, 1, 101)
rmse_scores = [ensemble_val_rmse(w) for w in weights_grid]

best_idx = np.argmin(rmse_scores)
best_w1_grid = weights_grid[best_idx]

result = minimize_scalar(ensemble_val_rmse, bounds=(0, 1), method='bounded')
best_w1 = result.x
best_w2 = 1 - best_w1

print(f"Best w1 (CNN-LSTM-GRU weight) from grid search: {best_w1_grid:.3f}")
print(f"Best w1 (CNN-LSTM-GRU weight) from optimizer:   {best_w1:.3f}")
print(f"Best w2 (XGBoost weight):                        {best_w2:.3f}")
print(f"Validation RMSE at optimal weights: {ensemble_val_rmse(best_w1):.3f}")

# Plot RMSE vs weight to show it's a genuine, justified minimum (good for your paper's figures)
plt.figure(figsize=(10, 5))
plt.plot(weights_grid, rmse_scores, color='navy')
plt.axvline(best_w1, color='red', linestyle='--', label=f'Optimal w1 = {best_w1:.3f}')
plt.title('Validation RMSE vs Ensemble Weight (w1 = CNN-LSTM-GRU weight)')
plt.xlabel('w1 (weight on CNN-LSTM-GRU)')
plt.ylabel('Validation RMSE')
plt.legend()
plt.tight_layout()
plt.savefig("ensemble_weight_search.png", dpi=150)
plt.show()

"""# Cell 42 — Final Ensemble Predictions on Test Set"""

test_merged["ensemble_pred_aqi"] = (
    best_w1 * test_merged["dl_pred_aqi"] + best_w2 * test_merged["xgb_pred_aqi"]
)

plt.figure(figsize=(16, 6))
plt.plot(test_merged["date"], test_merged["actual_aqi"], label="Actual AQI", color="black", linewidth=1.2)
plt.plot(test_merged["date"], test_merged["dl_pred_aqi"], label="CNN-LSTM-GRU (agg.)", color="crimson", alpha=0.6)
plt.plot(test_merged["date"], test_merged["xgb_pred_aqi"], label="XGBoost", color="green", alpha=0.6)
plt.plot(test_merged["date"], test_merged["ensemble_pred_aqi"], label="Weighted Ensemble", color="blue", linewidth=2)
plt.title("Actual vs Predicted AQI — Test Set — All Models")
plt.xlabel("Date")
plt.ylabel("AQI")
plt.legend()
plt.tight_layout()
plt.savefig("final_ensemble_comparison.png", dpi=150)
plt.show()

test_merged.to_csv("final_ensemble_predictions.csv", index=False)
print("Ensemble predictions saved to final_ensemble_predictions.csv")

"""# Cell 43 — Reusable Evaluation Metrics Function"""

def evaluate_model(y_true, y_pred, model_name, train_time=None, inference_time=None):
    y_true = np.array(y_true).flatten()
    y_pred = np.array(y_pred).flatten()

    mae = mean_absolute_error(y_true, y_pred)
    mse = mean_squared_error(y_true, y_pred)
    rmse = np.sqrt(mse)
    # Avoid divide-by-zero in MAPE by excluding near-zero actuals
    mask = y_true > 1e-3
    mape = np.mean(np.abs((y_true[mask] - y_pred[mask]) / y_true[mask])) * 100
    r2 = r2_score(y_true, y_pred)

    return {
        "Model": model_name,
        "MAE": round(mae, 3),
        "MSE": round(mse, 3),
        "RMSE": round(rmse, 3),
        "MAPE (%)": round(mape, 3),
        "R2": round(r2, 4),
        "Train Time (s)": round(train_time, 2) if isinstance(train_time, (int, float)) else (train_time if train_time else "-"),
        "Inference Time (s)": round(inference_time, 4) if isinstance(inference_time, (int, float)) else (inference_time if inference_time else "-")
    }

results = []

"""# Cell 44 — Baseline 1: Linear Regression (Daily)"""

from sklearn.linear_model import LinearRegression

start = time.time()
lr_model = LinearRegression()
lr_model.fit(daily_train_X, daily_train_y.ravel())
lr_train_time = time.time() - start

start = time.time()
lr_pred_scaled = lr_model.predict(daily_test_X)
lr_inference_time = time.time() - start

lr_pred = daily_scaler_y.inverse_transform(lr_pred_scaled.reshape(-1, 1))

results.append(evaluate_model(xgb_test_actual, lr_pred, "Linear Regression",
                               lr_train_time, lr_inference_time))
print(results[-1])

"""# Cell 45 — Baseline 2: Random Forest (Daily)"""

from sklearn.ensemble import RandomForestRegressor

start = time.time()
rf_model = RandomForestRegressor(n_estimators=300, max_depth=10, random_state=42, n_jobs=-1)
rf_model.fit(daily_train_X, daily_train_y.ravel())
rf_train_time = time.time() - start

start = time.time()
rf_pred_scaled = rf_model.predict(daily_test_X)
rf_inference_time = time.time() - start

rf_pred = daily_scaler_y.inverse_transform(rf_pred_scaled.reshape(-1, 1))

results.append(evaluate_model(xgb_test_actual, rf_pred, "Random Forest",
                               rf_train_time, rf_inference_time))
print(results[-1])

"""# Cell 46 — Baseline 3: Standalone LSTM (Hourly)"""

def build_lstm_only(n_timesteps, n_features):
    model = Sequential([
        Input(shape=(n_timesteps, n_features)),
        LSTM(64, return_sequences=True),
        Dropout(0.2),
        LSTM(32, return_sequences=False),
        Dense(16, activation='relu'),
        Dense(1)
    ])
    model.compile(optimizer=Adam(0.001), loss='mse', metrics=['mae'])
    return model

lstm_model = build_lstm_only(n_timesteps, n_features)

start = time.time()
lstm_model.fit(
    X_train_seq, y_train_seq,
    validation_data=(X_val_seq, y_val_seq),
    epochs=1, batch_size=64,
    callbacks=[EarlyStopping(monitor='val_loss', patience=8, restore_best_weights=True)],
    verbose=0
)
lstm_train_time = time.time() - start

start = time.time()
lstm_pred_scaled = lstm_model.predict(X_test_seq)
lstm_inference_time = time.time() - start

lstm_pred = hourly_scaler_y.inverse_transform(lstm_pred_scaled)

results.append(evaluate_model(y_test_actual, lstm_pred, "LSTM (standalone)",
                               lstm_train_time, lstm_inference_time))
print(results[-1])

"""# Cell 47 — Baseline 4: Standalone GRU (Hourly)"""

def build_gru_only(n_timesteps, n_features):
    model = Sequential([
        Input(shape=(n_timesteps, n_features)),
        GRU(64, return_sequences=True),
        Dropout(0.2),
        GRU(32, return_sequences=False),
        Dense(16, activation='relu'),
        Dense(1)
    ])
    model.compile(optimizer=Adam(0.001), loss='mse', metrics=['mae'])
    return model

gru_model = build_gru_only(n_timesteps, n_features)

start = time.time()
gru_model.fit(
    X_train_seq, y_train_seq,
    validation_data=(X_val_seq, y_val_seq),
    epochs=1, batch_size=64,
    callbacks=[EarlyStopping(monitor='val_loss', patience=8, restore_best_weights=True)],
    verbose=0
)
gru_train_time = time.time() - start

start = time.time()
gru_pred_scaled = gru_model.predict(X_test_seq)
gru_inference_time = time.time() - start

gru_pred = hourly_scaler_y.inverse_transform(gru_pred_scaled)

results.append(evaluate_model(y_test_actual, gru_pred, "GRU (standalone)",
                               gru_train_time, gru_inference_time))
print(results[-1])

"""# Cell 48 — Add CNN-LSTM-GRU and XGBoost (Reuse Earlier Results)"""

# CNN-LSTM-GRU (hourly) — from Cell 25/28, already trained
start = time.time()
_ = final_dl_model.predict(X_test_seq)
cnn_lstm_gru_inference_time = time.time() - start

results.append(evaluate_model(y_test_actual, y_test_pred, "CNN-LSTM-GRU",
                               train_time="Not recorded", inference_time=cnn_lstm_gru_inference_time))

# XGBoost (daily) — from Cell 33/34
results.append(evaluate_model(xgb_test_actual, xgb_test_pred, "XGBoost",
                               xgb_train_time, xgb_inference_time))

print(results[-2])
print(results[-1])

"""# Cell 49 — Add the Final Ensemble (on Aligned Test Dates)"""

ensemble_metrics = evaluate_model(
    test_merged["actual_aqi"], test_merged["ensemble_pred_aqi"],
    "CNN-LSTM-GRU + XGBoost Ensemble",
    train_time=None,  # ensemble itself needs no extra training, just weight search
    inference_time=None
)
results.append(ensemble_metrics)
print(ensemble_metrics)

"""# Cell 50 — Final Comparison Table"""

results_df = pd.DataFrame(results)
results_df = results_df.sort_values("RMSE").reset_index(drop=True)

print(results_df.to_string(index=False))
results_df.to_csv("model_comparison_results.csv", index=False)

"""# Cell 51 — Model Comparison Bar Charts"""

fig, axes = plt.subplots(2, 2, figsize=(16, 12))

sns.barplot(data=results_df, x="RMSE", y="Model", ax=axes[0,0], palette="rocket")
axes[0,0].set_title("RMSE Comparison (lower is better)")

sns.barplot(data=results_df, x="MAE", y="Model", ax=axes[0,1], palette="mako")
axes[0,1].set_title("MAE Comparison (lower is better)")

sns.barplot(data=results_df, x="R2", y="Model", ax=axes[1,0], palette="viridis")
axes[1,0].set_title("R² Comparison (higher is better)")

sns.barplot(data=results_df, x="MAPE (%)", y="Model", ax=axes[1,1], palette="crest")
axes[1,1].set_title("MAPE Comparison (lower is better)")

# plt.tight_layout()
# plt.savefig("model_comparison_charts.png", dpi=150)
# plt.show()

"""# Cell 52 — Load Everything Needed for Single-Date Prediction"""

import joblib
import json

# Reload trained XGBoost model + scalers + feature list
final_xgb_model = xgb.XGBRegressor()
final_xgb_model.load_model("final_xgboost_model.json")

daily_scaler_X = joblib.load("daily_scaler_X.pkl")
daily_scaler_y = joblib.load("daily_scaler_y.pkl")

with open("feature_columns.json") as f:
    feature_cols = json.load(f)
daily_feature_cols = feature_cols["daily"]

# Reconstruct the FULL feature-engineered daily dataframe (with lag/rolling/calendar columns)
# from the train/val/test splits made in Cell 18 — these already have every column in daily_feature_cols
daily_full = pd.concat([daily_train, daily_val, daily_test], ignore_index=True)
daily_full = daily_full.sort_values("datetime").reset_index(drop=True)

print("daily_full shape:", daily_full.shape)
print("Has all feature columns:", set(daily_feature_cols).issubset(daily_full.columns))

"""# Cell 53 — Predict AQI for a User-Given Date"""

def predict_aqi_for_date(date_str):
    target_date = pd.to_datetime(date_str)
    last_known_date = daily_full["datetime"].max()

    # -------- CASE 1: Date exists in historical data --------
    if target_date <= last_known_date:
        row = daily_full[daily_full["datetime"] == target_date]
        if row.empty:
            print(f"No record found for {date_str} (check date format / range: "
                  f"{daily_full['datetime'].min().date()} to {last_known_date.date()})")
            return None

        X_row = row[daily_feature_cols]
        X_scaled = daily_scaler_X.transform(X_row)
        pred_scaled = final_xgb_model.predict(X_scaled).reshape(-1, 1)
        pred_aqi = daily_scaler_y.inverse_transform(pred_scaled)[0][0]
        actual_aqi = row["AQI"].values[0]

        print(f"Date: {date_str}  (historical)")
        print(f"Predicted AQI: {pred_aqi:.2f}")
        print(f"Actual AQI:    {actual_aqi:.2f}")
        print(f"Absolute Error: {abs(pred_aqi - actual_aqi):.2f}")
        return pred_aqi

    # -------- CASE 2: Future date beyond dataset --------
    else:
        print(f"Date: {date_str}  (future — beyond last recorded date {last_known_date.date()})")
        print("NOTE: Future pollutant levels are unknown. Using the historical seasonal "
              "average for that calendar month as a proxy — treat this as an approximation, "
              "not a true forecast, and state this limitation in your report.\n")

        days_ahead = (target_date - last_known_date).days
        history = daily_full.copy()

        # Recursive day-by-day forecasting
        for step in range(1, days_ahead + 1):
            next_date = last_known_date + pd.Timedelta(days=step)
            month = next_date.month

            # Approximate pollutant features using historical same-month average
            month_avg = history[history["datetime"].dt.month == month][pollutant_cols].mean()

            new_row = {col: month_avg[col] for col in pollutant_cols}
            new_row["datetime"] = next_date
            new_row["month"] = month
            new_row["weekday"] = next_date.weekday()
            new_row["is_weekend"] = int(next_date.weekday() >= 5)
            new_row["day_of_year"] = next_date.dayofyear
            new_row["season"] = (0 if month in [12,1,2] else 1 if month in [3,4,5]
                                  else 2 if month in [6,7,8,9] else 3)

            # Lag features come from actual/predicted AQI history
            for lag in [1, 2, 3, 7, 14, 30]:
                lag_date = next_date - pd.Timedelta(days=lag)
                match = history[history["datetime"] == lag_date]
                new_row[f"AQI_lag{lag}"] = match["AQI"].values[0] if not match.empty else history["AQI"].mean()

            # Rolling features from recent history
            for w in [3, 7, 14]:
                recent = history[history["datetime"] < next_date].tail(w)["AQI"]
                new_row[f"AQI_rollmean{w}"] = recent.mean()
                new_row[f"AQI_rollstd{w}"] = recent.std()
                new_row[f"AQI_rollmax{w}"] = recent.max()
                new_row[f"AQI_rollmin{w}"] = recent.min()

            X_row = pd.DataFrame([new_row])[daily_feature_cols]
            X_scaled = daily_scaler_X.transform(X_row)
            pred_scaled = final_xgb_model.predict(X_scaled).reshape(-1, 1)
            pred_aqi = daily_scaler_y.inverse_transform(pred_scaled)[0][0]

            new_row["AQI"] = pred_aqi
            history = pd.concat([history, pd.DataFrame([new_row])], ignore_index=True)

        final_pred = history[history["datetime"] == target_date]["AQI"].values[0]
        print(f"Predicted AQI for {date_str}: {final_pred:.2f}")
        return final_pred

# Run the user input block (mocked loop for automated prediction output)
test_dates = ["2020-07-02", "2024-04-01", "2026-07-12"]
for user_date in test_dates:
    try:
        predicted_value = predict_aqi_for_date(user_date)
        print(f"Predicted AQI value for {user_date} via predict_aqi_for_date: {predicted_value:.2f}")
    except Exception as e:
        print(f"Error predicting for {user_date}: {e}")

# =====================================================================
# CELL 55 — Preprocessing, Time Features, and Sequencing (KeyError Fixed)
# =====================================================================
df_model = daily.copy()

# 1. Safely pull out 'Date' if it is hidden in the DataFrame index
if 'Date' not in df_model.columns and 'date' not in df_model.columns:
    df_model = df_model.reset_index()

# 2. Automatically find and rename any column variation to exactly 'Date'
for col in df_model.columns:
    if 'date' in str(col).lower():
        df_model.rename(columns={col: 'Date'}, inplace=True)
        break

# Convert to datetime format safely
df_model['Date'] = pd.to_datetime(df_model['Date'])

# Linear forward/backward fill to guarantee sequence integrity
df_model = df_model.ffill().bfill()

# Extract Calendar Features directly into the DataFrame columns
df_model['Month'] = df_model['Date'].dt.month
df_model['Day'] = df_model['Date'].dt.day
df_model['DayOfWeek'] = df_model['Date'].dt.dayofweek
df_model['DayOfYear'] = df_model['Date'].dt.dayofyear
df_model['Year'] = df_model['Date'].dt.year

feature_cols = ['PM2.5', 'PM10', 'NO', 'NO2', 'NOx', 'NH3', 'CO', 'SO2', 'O3']
target_col = 'AQI'

# Fit Scalers
scaler_X = MinMaxScaler()
scaler_y = MinMaxScaler()
df_scaled_X = scaler_X.fit_transform(df_model[feature_cols])
df_scaled_y = scaler_y.fit_transform(df_model[[target_col]])

# Create Moving Lookback Sequences for CNN-LSTM-GRU
LOOKBACK_WINDOW = 30
X_seq, y_target, time_features = [], [], []

for i in range(LOOKBACK_WINDOW, len(df_model)):
    X_seq.append(df_scaled_X[i-LOOKBACK_WINDOW:i])
    y_target.append(df_scaled_y[i])
    # Extract structural calendar markers matching the forecast target day
    time_features.append(df_model[['Month', 'Day', 'DayOfWeek', 'DayOfYear', 'Year']].iloc[i].values)

X_seq = np.array(X_seq)
y_target = np.array(y_target).ravel()
time_features = np.array(time_features)

# Split Chronologically (80% Train, 20% Test)
split_idx = int(len(X_seq) * 0.8)
X_train_seq, X_test_seq = X_seq[:split_idx], X_seq[split_idx:]
time_train, time_test = time_features[:split_idx], time_features[split_idx:]
y_train, y_test = y_target[:split_idx], y_target[split_idx:]

print("Sequences, 'time_train', and 'time_test' matrices successfully created with fixed Date tracking!")

# =====================================================================
# CELL 56 — Training the Calendar-Aware Hybrid Architecture
# =====================================================================
import os
# Suppress TensorFlow GPU diagnostic logs and warnings
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

import xgboost as xgb
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Conv1D, LSTM, GRU, Dense, Dropout

# Define the CNN + LSTM + GRU Spatiotemporal Extractor
model_inputs = Input(shape=(X_train_seq.shape[1], X_train_seq.shape[2]))

# CNN Extraction Layers
x = Conv1D(filters=64, kernel_size=3, activation='relu', padding='same')(model_inputs)
x = Conv1D(filters=32, kernel_size=3, activation='relu', padding='same')(x)

# Recurrent Layers for Temporal Tracking
x = LSTM(64, return_sequences=True)(x)
x = Dropout(0.2)(x)
x = GRU(32, return_sequences=False)(x)
x = Dropout(0.2)(x)

# Hidden Bottleneck Embedding
extracted_embeddings = Dense(16, activation='relu', name='deep_features_layer')(x)

# Compile and train the spatiotemporal feature extractor on the daily targets
output = Dense(1)(extracted_embeddings)
full_model = Model(inputs=model_inputs, outputs=output)
full_model.compile(optimizer='adam', loss='mse')
print("Training the daily CNN-LSTM-GRU spatiotemporal model...")
full_model.fit(X_train_seq, y_train, epochs=8, batch_size=32, verbose=1)

feature_extractor_model = Model(inputs=model_inputs, outputs=extracted_embeddings)

# Extract deep sequential features from history windows
print("Generating sequential feature vectors from CNN-LSTM-GRU layers...")
X_train_seq_feats = feature_extractor_model.predict(X_train_seq, verbose=0)
X_test_seq_feats = feature_extractor_model.predict(X_test_seq, verbose=0)

# CONCATENATE Deep Sequence Traits with the Day-by-Day Calendar Features
X_train_combined = np.hstack([X_train_seq_feats, time_train])
X_test_combined = np.hstack([X_test_seq_feats, time_test])

# Train final XGBoost Regressor on the combined multi-modal dataset
print("Training the calendar-aware XGBoost Regressor...")
xgb_model = xgb.XGBRegressor(
    n_estimators=200,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)
xgb_model.fit(X_train_combined, y_train)
print("Hybrid training completed successfully!")

print("Saving daily hybrid model artifacts to models/...")
import os
import joblib
os.makedirs("models", exist_ok=True)
feature_extractor_model.save("models/deep_learning_model.keras")
xgb_model.save_model("models/xgboost_model.json")
joblib.dump(scaler_X, "models/scaler.joblib")
joblib.dump(scaler_y, "models/scaler_y.joblib")
print("Saved models/deep_learning_model.keras, models/xgboost_model.json, models/scaler.joblib, models/scaler_y.joblib successfully!")

# =====================================================================
# CELL 57 — Dynamic Daily Future Forecasting Engine (Warning Suppressed)
# =====================================================================
import warnings
# Explicitly turn off Sklearn feature names UserWarnings
warnings.filterwarnings("ignore", category=UserWarning)

def get_aqi_bucket(aqi_value):
    """
    Categorizes the numeric AQI into the official CPCB Indian AQI standard buckets.
    """
    if aqi_value <= 50:
        return "Good"
    elif aqi_value <= 100:
        return "Satisfactory"
    elif aqi_value <= 200:
        return "Moderate"
    elif aqi_value <= 300:
        return "Poor"
    elif aqi_value <= 400:
        return "Very Poor"
    else:
        return "Severe"

def predict_future_date_dynamic(target_date_str):
    """
    Predicts a unique dynamic AQI, individual pollutant levels, and the corresponding
    AQI category bucket for any future day past 2020.
    """
    try:
        target_date = pd.to_datetime(target_date_str)
        if target_date.year > 2100 or target_date.year < 2000:
            return "❌ Input Error: Year out of plausible bounds. Please use the YYYY-MM-DD format (e.g., 2026-07-08)."
    except Exception:
        return "❌ DateParseError: Invalid date format. Please format your entry strictly as YYYY-MM-DD."

    df_temp = df_model.copy()

    # Safely extract Date column
    if 'Date' not in df_temp.columns and 'date' not in df_temp.columns:
        df_temp = df_temp.reset_index()
    for col in df_temp.columns:
        if 'date' in str(col).lower():
            df_temp.rename(columns={col: 'Date'}, inplace=True)
            break

    df_temp['Date'] = pd.to_datetime(df_temp['Date'])

    feature_cols = ['PM2.5', 'PM10', 'NO', 'NO2', 'NOx', 'NH3', 'CO', 'SO2', 'O3']
    target_col = 'AQI'
    local_profile = df_temp.groupby(['Month', 'Day'])[feature_cols].mean().reset_index()

    last_historical_date = df_temp['Date'].max()

    # -------- CASE 1: Date exists in historical data --------
    if target_date <= last_historical_date:
        match = df_temp[df_temp['Date'].dt.date == target_date.date()]
        if not match.empty:
            actual_aqi = match['AQI'].values[0]
            out_str = f"Historical Date Found! Actual AQI on {target_date_str}: {actual_aqi:.2f} ({get_aqi_bucket(actual_aqi)})\n"
            out_str += "=========================================\n"
            out_str += "📊 RECORDED POLLUTANT VALUES:\n"
            out_str += "=========================================\n"
            for col in feature_cols:
                out_str += f" -> {col:7}: {match[col].values[0]:.2f}\n"
            return out_str
        return "Date falls within dataset limits but has missing entries."

    # -------- CASE 2: True Future Forecasting --------
    days_to_forecast = (target_date - last_historical_date).days
    print(f"Projecting {days_to_forecast} days forward beyond {last_historical_date.strftime('%Y-%m-%d')}...")

    current_window = df_scaled_X[-LOOKBACK_WINDOW:].copy()
    latest_predicted_aqi = None
    final_pollutants_scaled = None

    for step in range(days_to_forecast):
        current_step_date = last_historical_date + pd.Timedelta(days=step + 1)
        m = current_step_date.month
        d = current_step_date.day

        input_window = current_window.reshape(1, LOOKBACK_WINDOW, -1)
        deep_features = feature_extractor_model(input_window, training=False).numpy()

        current_time_feats = np.array([[
            m, d, current_step_date.dayofweek, current_step_date.dayofyear, current_step_date.year
        ]])

        xgb_input = np.hstack([deep_features, current_time_feats])

        scaled_pred_aqi = xgb_model.predict(xgb_input)[0]

        # Wrapped as a pandas DataFrame with matched feature names to satisfy the scaler
        pred_df = pd.DataFrame([[scaled_pred_aqi]], columns=[target_col])
        latest_predicted_aqi = scaler_y.inverse_transform(pred_df)[0][0]

        profile_row = local_profile[(local_profile['Month'] == m) & (local_profile['Day'] == d)]
        if not profile_row.empty:
            raw_pollutants = profile_row[feature_cols].copy()
        else:
            raw_pollutants = pd.DataFrame([local_profile[feature_cols].mean().values], columns=feature_cols)

        final_pollutants_scaled = scaler_X.transform(raw_pollutants)
        current_window = np.vstack([current_window[1:], final_pollutants_scaled[0]])

    # Wrapped matching feature name format cleanly
    pollutants_df = pd.DataFrame(final_pollutants_scaled, columns=feature_cols)
    pollutants_unscaled = scaler_X.inverse_transform(pollutants_df)[0]

    # Build clean layout output strings (No emojis to prevent Windows console charmap encoding errors)
    result_string = f"Predicted Future AQI for [{target_date_str}]: {latest_predicted_aqi:.2f}\n"
    result_string += f"Air Quality Category Bucket: {get_aqi_bucket(latest_predicted_aqi)}\n"
    result_string += "=========================================\n"
    result_string += "ESTIMATED INDIVIDUAL POLLUTANT VALUES:\n"
    result_string += "=========================================\n"
    for name, val in zip(feature_cols, pollutants_unscaled):
        result_string += f" -> {name:7}: {val:.2f}\n"

    return result_string

# Run the user input block (mocked loop for automated prediction output - commented out for speed)
# test_dates = ["2020-07-02", "2024-04-01", "2026-07-12"]
# for user_date in test_dates:
#     try:
#         prediction_result = predict_future_date_dynamic(user_date)
#         print(f"\nPredictions for {user_date}:")
#         print(prediction_result)
#     except Exception as e:
#         print(f"Error predicting for {user_date}: {e}")